RailsBootstrap::Application.routes.draw do
  resources :visitors, only: [:new, :create]
  root :to => 'visitors#new'
end

#Order is significant in the routes.rb file. As the final designated root path will only be active 
#if nothing above it matches the route.

#the new route has these properties
# new_visitor_path - route helper that generates a URL. 
#visitors - the name of the controller (VisitorsController)
#new - the controller action
#an http:// URL generated by the route helper
#GET - HTTP protocol to display a page

#the create route has these properties
#visitor_path - route helper that generates a desination URL for form data submission
#visitors - name of the controller
#create - name of the controller action. 
# an http:// URL generated by route helper
# POST - an HTTP protcol to submit form data
